# templates.py — Industry templates for OptiFlow

INDUSTRY_TEMPLATES = {
    "food_manufacturing": {
        "label": "Food",
        "icon": "🍪",
        "description": "Cookie, bakery, and food production lines",
        "stages": [
            {"name": "Mixer",          "output_per_cycle": 1,   "cycle_time": 8,  "scaling": 360, "machines": 1},
            {"name": "Dough Extruder", "output_per_cycle": 400, "cycle_time": 4,  "scaling": 1,   "machines": 2},
            {"name": "Shelf",          "output_per_cycle": 600, "cycle_time": 10, "scaling": 1,   "machines": 3},
            {"name": "Oven",           "output_per_cycle": 300, "cycle_time": 12, "scaling": 1,   "machines": 1},
            {"name": "Cooling Rack",   "output_per_cycle": 600, "cycle_time": 20, "scaling": 1,   "machines": 2},
            {"name": "Packager",       "output_per_cycle": 100, "cycle_time": 3,  "scaling": 1,   "machines": 1},
        ],
        "default_target": 26577,
        "default_shift_hours": 12,
    },
    "electronics_assembly": {
        "label": "Electronics",
        "icon": "🔌",
        "description": "PCB, component assembly, and electronics manufacturing",
        "stages": [
            {"name": "PCB Loading",    "output_per_cycle": 50,  "cycle_time": 2, "scaling": 1, "machines": 1},
            {"name": "SMT Placement",  "output_per_cycle": 30,  "cycle_time": 5, "scaling": 1, "machines": 1},
            {"name": "Reflow Oven",    "output_per_cycle": 40,  "cycle_time": 8, "scaling": 1, "machines": 1},
            {"name": "Inspection",     "output_per_cycle": 60,  "cycle_time": 3, "scaling": 1, "machines": 1},
            {"name": "Testing",        "output_per_cycle": 20,  "cycle_time": 6, "scaling": 1, "machines": 1},
            {"name": "Packaging",      "output_per_cycle": 80,  "cycle_time": 2, "scaling": 1, "machines": 1},
        ],
        "default_target": 5000,
        "default_shift_hours": 8,
    },
    "automotive_parts": {
        "label": "Automotive",
        "icon": "🚗",
        "description": "Automotive component and parts manufacturing",
        "stages": [
            {"name": "Stamping",       "output_per_cycle": 20,  "cycle_time": 4,  "scaling": 1, "machines": 1},
            {"name": "Welding",        "output_per_cycle": 15,  "cycle_time": 6,  "scaling": 1, "machines": 1},
            {"name": "Machining",      "output_per_cycle": 10,  "cycle_time": 10, "scaling": 1, "machines": 1},
            {"name": "Heat Treatment", "output_per_cycle": 25,  "cycle_time": 15, "scaling": 1, "machines": 1},
            {"name": "Quality Check",  "output_per_cycle": 30,  "cycle_time": 3,  "scaling": 1, "machines": 1},
            {"name": "Packaging",      "output_per_cycle": 40,  "cycle_time": 2,  "scaling": 1, "machines": 1},
        ],
        "default_target": 2000,
        "default_shift_hours": 8,
    },
    "textile_garment": {
        "label": "Textile",
        "icon": "👕",
        "description": "Textile processing and garment production",
        "stages": [
            {"name": "Cutting",       "output_per_cycle": 100, "cycle_time": 5,  "scaling": 1, "machines": 1},
            {"name": "Sewing",        "output_per_cycle": 20,  "cycle_time": 12, "scaling": 1, "machines": 1},
            {"name": "Pressing",      "output_per_cycle": 50,  "cycle_time": 4,  "scaling": 1, "machines": 1},
            {"name": "Quality Check", "output_per_cycle": 80,  "cycle_time": 3,  "scaling": 1, "machines": 1},
            {"name": "Folding",       "output_per_cycle": 120, "cycle_time": 2,  "scaling": 1, "machines": 1},
            {"name": "Packaging",     "output_per_cycle": 150, "cycle_time": 2,  "scaling": 1, "machines": 1},
        ],
        "default_target": 3000,
        "default_shift_hours": 8,
    },
    "pharmaceutical": {
        "label": "Pharma",
        "icon": "💊",
        "description": "Pharmaceutical and medical product manufacturing",
        "stages": [
            {"name": "Weighing",     "output_per_cycle": 200,  "cycle_time": 5,  "scaling": 1, "machines": 1},
            {"name": "Blending",     "output_per_cycle": 500,  "cycle_time": 15, "scaling": 1, "machines": 1},
            {"name": "Tablet Press", "output_per_cycle": 1000, "cycle_time": 8,  "scaling": 1, "machines": 1},
            {"name": "Coating",      "output_per_cycle": 800,  "cycle_time": 10, "scaling": 1, "machines": 1},
            {"name": "Inspection",   "output_per_cycle": 600,  "cycle_time": 4,  "scaling": 1, "machines": 1},
            {"name": "Packaging",    "output_per_cycle": 400,  "cycle_time": 3,  "scaling": 1, "machines": 1},
        ],
        "default_target": 50000,
        "default_shift_hours": 8,
    },
    "custom": {
        "label": "Custom",
        "icon": "📝",
        "description": "Start from scratch with your own production line",
        "stages": [
            {"name": "Stage 1", "output_per_cycle": 100, "cycle_time": 5, "scaling": 1, "machines": 1},
            {"name": "Stage 2", "output_per_cycle": 100, "cycle_time": 5, "scaling": 1, "machines": 1},
            {"name": "Stage 3", "output_per_cycle": 100, "cycle_time": 5, "scaling": 1, "machines": 1},
        ],
        "default_target": 5000,
        "default_shift_hours": 8,
    },
}
